
title: Kashurpedia
email: you@example.com
description: "A fully custom, SEO-ready Jekyll blog ready for Cloudflare Pages or GitHub Pages."
baseurl: ""
url: "https://kashurpedia.pages.dev"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
exclude:
  - node_modules
  - vendor/bundle
  - Gemfile.lock

excerpt_separator: "<!--more-->"

author:
  name: "Your Name"
  email: you@example.com

social:
  twitter: your_twitter_handle
  github: itzfew
