title: My Articles Blog
email: you@example.com
description: >- 
  A simple article site with admin approval.
baseurl: "" 
url: "https://kashurpedia.pages.dev" # replace with your repo URL

theme: minima

plugins:
  - jekyll-feed
